
import random

def quiz_user(words, num_questions):

    return random.sample(words, num_questions)

def check_answer(word, user_answer, language):

    return user_answer == word[language].lower()

words = [
    {'french': 'être', 'english': 'be', 'turkish': 'olmak'},
    {'french': 'avoir', 'english': 'have', 'turkish': 'var'},
    {'french': 'pour', 'english': 'for', 'turkish': 'için'},
    {'french': 'dans', 'english': 'in', 'turkish': 'içinde'},
    {'french': 'plus', 'english': 'more', 'turkish': 'daha fazla'},
    {'french': 'pouvoir', 'english': 'power', 'turkish': 'güç'},
    {'french': 'je', 'english': 'me', 'turkish': 'ben'},
    {'french': 'avec', 'english': 'with', 'turkish': 'ile'},
    {'french': 'tout', 'english': 'all', 'turkish': 'hepsi'},
    {'french': 'faire', 'english': 'go to', 'turkish': 'şuraya git'},
    {'french': 'son', 'english': 'son', 'turkish': 'oğul'},
    {'french': 'mettre', 'english': 'put', 'turkish': 'koy'},
    {'french': 'autre', 'english': 'other', 'turkish': 'diğer'},
    {'french': 'on', 'english': 'on', 'turkish': 'üzerinde'},
    {'french': 'mais', 'english': 'more', 'turkish': 'daha fazla'},
    {'french': 'nous', 'english': 'nous', 'turkish': 'nous'},
    {'french': 'comme', 'english': 'as', 'turkish': 'olarak'},
    {'french': 'ou', 'english': 'ou', 'turkish': 'ou'},
    {'french': 'si', 'english': 'si', 'turkish': 'si'},
    {'french': 'leur', 'english': 'their', 'turkish': 'onların'},
    {'french': 'y', 'english': 'y', 'turkish': 'y'},
    {'french': 'dire', 'english': 'dire', 'turkish': 'korkunç'},
    {'french': 'elle', 'english': 'she', 'turkish': 'o'},
    {'french': 'devoir', 'english': 'homework', 'turkish': 'ev ödevi'},
    {'french': 'avant', 'english': 'before', 'turkish': 'önce'},
    {'french': 'deux', 'english': 'two', 'turkish': 'iki'},
    {'french': 'même', 'english': 'even', 'turkish': 'Hatta'},
    {'french': 'prendre', 'english': 'take', 'turkish': 'al'},
    {'french': 'aussi', 'english': 'also', 'turkish': 'Ayrıca'},
    {'french': 'celui', 'english': 'the one', 'turkish': 'bir'},
    {'french': 'donner', 'english': 'give', 'turkish': 'ver'},
    {'french': 'bien', 'english': 'well', 'turkish': 'iyi'},
    {'french': 'où', 'english': 'où', 'turkish': 'où'},
    {'french': 'fois', 'english': 'once', 'turkish': 'bir kez'},
    {'french': 'vous', 'english': 'vous', 'turkish': 'vous'},
    {'french': 'petit', 'english': 'small', 'turkish': 'küçük'},
    {'french': 'plus', 'english': 'more', 'turkish': 'daha fazla'},
    {'french': 'aller', 'english': 'go', 'turkish': 'git'},
    {'french': 'jour', 'english': 'day', 'turkish': 'gün'},
    {'french': 'très', 'english': 'very', 'turkish': 'çok'},
    {'french': 'faire', 'english': 'go to', 'turkish': 'şuraya git'},
    {'french': 'rien', 'english': 'nothing', 'turkish': 'hiçbir şey'},
    {'french': 'grand', 'english': 'large', 'turkish': 'büyük'},
    {'french': 'encore', 'english': 'still', 'turkish': 'Sessiz'},
    {'french': 'voir', 'english': 'see', 'turkish': 'bkz.'},
    {'french': 'celui', 'english': 'the one', 'turkish': 'bir'},
    {'french': 'sans', 'english': 'without', 'turkish': 'olmadan'},
    {'french': 'homme', 'english': 'man', 'turkish': 'adam'},
    {'french': 'temps', 'english': 'time', 'turkish': 'zaman'},
    {'french': 'nouveau', 'english': 'new', 'turkish': 'yeni'},
    {'french': 'après', 'english': 'after', 'turkish': 'sonra'},
    {'french': 'année', 'english': 'year', 'turkish': 'yıl'},
    {'french': 'là', 'english': 'là', 'turkish': 'là'},
    {'french': 'bon', 'english': 'bon', 'turkish': 'bon'},
    {'french': 'alors', 'english': 'then', 'turkish': 'sonra'},
    {'french': 'quelque', 'english': 'some', 'turkish': 'bazı'},
    {'french': 'venir', 'english': 'visit', 'turkish': 'ziyaret'},
    {'french': 'dont', 'english': 'of which', 'turkish': 'hangi'},
    {'french': 'ainsi', 'english': 'so', 'turkish': 'Yani'},
    {'french': 'car', 'english': 'car', 'turkish': 'araba'},
    {'french': 'peu', 'english': 'peu', 'turkish': 'peu'},
    {'french': 'moins', 'english': 'less', 'turkish': 'daha az'},
    {'french': 'vie', 'english': 'vie', 'turkish': 'vie'},
    {'french': 'trois', 'english': 'three', 'turkish': 'üç'},
    {'french': 'pays', 'english': 'country', 'turkish': 'ülke'},
    {'french': 'monde', 'english': 'world', 'turkish': 'Dünya'},
    {'french': 'entre', 'english': 'on', 'turkish': 'üzerinde'},
    {'french': 'chose', 'english': 'chose', 'turkish': 'seçti'},
    {'french': 'femme', 'english': 'woman', 'turkish': 'kadın'},
    {'french': 'premier', 'english': 'first', 'turkish': 'önce'},
    {'french': 'dernier', 'english': 'last', 'turkish': 'son'},
    {'french': 'jamais', 'english': 'jamais', 'turkish': 'jamais'},
    {'french': 'trouver', 'english': 'find', 'turkish': 'bulmak'},
    {'french': 'mer', 'english': 'mer', 'turkish': 'mer'},
    {'french': 'état', 'english': 'status', 'turkish': 'durum'},
    {'french': 'falloir', 'english': 'falloir', 'turkish': 'falloir'},
    {'french': 'chaque', 'english': 'every', 'turkish': 'her'},
    {'french': 'parler', 'english': 'speak', 'turkish': 'konuşmak'},
    {'french': 'mettre', 'english': 'put', 'turkish': 'koy'},
    {'french': 'jeune', 'english': 'young', 'turkish': 'genç'},
    {'french': 'moment', 'english': 'moment', 'turkish': 'an'},
    {'french': 'pendant', 'english': 'for', 'turkish': 'için'},
    {'french': 'sans', 'english': 'without', 'turkish': 'olmadan'},
    {'french': 'autre', 'english': 'other', 'turkish': 'diğer'},
    {'french': 'vers', 'english': 'vers', 'turkish': 'vers'},
    {'french': 'toujours', 'english': 'always', 'turkish': 'her zaman'},
    {'french': 'maison', 'english': 'home', 'turkish': 'ev'},
    {'french': 'partie', 'english': 'part', 'turkish': 'parça'},
    {'french': 'point', 'english': 'point', 'turkish': 'nokta'},
    {'french': "aujourd'hui", 'english': 'today', 'turkish': 'bugün'},
    {'french': 'père', 'english': 'father', 'turkish': 'Baba'},
    {'french': 'regarder', 'english': 'regarder', 'turkish': 'saygıdeğer'},
    {'french': 'politique', 'english': 'policy', 'turkish': 'Politika'},
    {'french': 'enfant', 'english': 'child', 'turkish': 'Çocuk'},
    {'french': 'histoire', 'english': 'history', 'turkish': 'TARİH'},
    {'french': 'sortir', 'english': 'go to', 'turkish': 'şuraya git'},
    {'french': 'main', 'english': 'main', 'turkish': 'ana'},
    {'french': 'vrai', 'english': 'real', 'turkish': 'gerçek'},
    {'french': 'côté', 'english': 'at', 'turkish': 'at'},
    {'french': 'place', 'english': 'place', 'turkish': 'yer'},
    {'french': 'alors', 'english': 'then', 'turkish': 'sonra'},
    {'french': 'ensemble', 'english': 'set', 'turkish': 'set'},
    {'french': 'marcher', 'english': 'walk', 'turkish': 'Yürümek'},
    {'french': 'début', 'english': 'start', 'turkish': 'başla'},
    {'french': 'mois', 'english': 'month', 'turkish': 'ay'},
    {'french': 'porter', 'english': 'porter', 'turkish': 'Porter'},
    {'french': 'loin', 'english': 'link', 'turkish': 'link'},
    {'french': 'fin', 'english': 'fin', 'turkish': 'fin'},
    {'french': 'croire', 'english': 'believe', 'turkish': 'inanmak'},
    {'french': 'plutôt', 'english': 'rather', 'turkish': 'daha ziyade'},
    {'french': 'penser', 'english': 'think', 'turkish': 'düşünmek'},
    {'french': 'quatre', 'english': 'four', 'turkish': 'dört'},
    {'french': 'permettre', 'english': 'enable', 'turkish': 'etkinleştir'},
    {'french': 'tenir', 'english': 'visit', 'turkish': 'ziyaret'},
    {'french': 'chef', 'english': 'chef', 'turkish': 'şef'},
    {'french': 'politique', 'english': 'policy', 'turkish': 'Politika'},
    {'french': 'pied', 'english': 'pied', 'turkish': 'alaca'},
    {'french': 'ville', 'english': 'city', 'turkish': 'ŞEHİR'},
    {'french': 'mer', 'english': 'mer', 'turkish': 'mer'},
    {'french': 'gens', 'english': 'gens', 'turkish': 'gens'},
    {'french': 'cas', 'english': 'cas', 'turkish': 'cas'},
    {'french': 'entendre', 'english': 'hear', 'turkish': 'duymak'},
    {'french': 'rendre', 'english': 'make', 'turkish': 'yapmak'},
    {'french': 'connaître', 'english': 'get to know', 'turkish': 'tanıyın'},
    {'french': 'type', 'english': 'type', 'turkish': 'tip'},
    {'french': 'corps', 'english': 'body', 'turkish': 'vücut'},
    {'french': 'dix', 'english': 'dix', 'turkish': 'dix'},
    {'french': 'reste', 'english': 'reste', 'turkish': 'reste'},
    {'french': 'long', 'english': 'long', 'turkish': 'uzun'},
    {'french': 'assez', 'english': 'quite', 'turkish': 'oldukça'},
    {'french': 'raison', 'english': 'reason', 'turkish': 'Sebep'},
    {'french': 'idée', 'english': 'idea', 'turkish': 'fikir'},
    {'french': 'matin', 'english': 'matin', 'turkish': 'matin'},
    {'french': 'suite', 'english': 'suite', 'turkish': 'süit'},
    {'french': 'peine', 'english': 'sentence', 'turkish': 'cümle'},
    {'french': 'seulement', 'english': 'only', 'turkish': 'sadece'},
    {'french': 'beaucoup', 'english': 'many', 'turkish': 'birçok'},
    {'french': 'personne', 'english': 'person', 'turkish': 'kişi'},
    {'french': 'soit', 'english': 'or', 'turkish': 'veya'},
    {'french': 'famille', 'english': 'family', 'turkish': 'AİLE'},
    {'french': 'vivre', 'english': 'live', 'turkish': 'canlı'},
    {'french': 'comprendre', 'english': 'understand', 'turkish': 'anlamak'},
    {'french': 'cause', 'english': 'cause', 'turkish': 'Çünkü'},
    {'french': 'perdu', 'english': 'lost', 'turkish': 'Kayıp'},
    {'french': 'tête', 'english': 'head', 'turkish': 'Kafa'},
    {'french': 'question', 'english': 'question', 'turkish': 'soru'},
    {'french': 'essayer', 'english': 'try', 'turkish': 'dene'},
    {'french': 'eau', 'english': 'eau', 'turkish': 'Eau'},
    {'french': 'manger', 'english': 'eat', 'turkish': 'yemek'},
    {'french': 'boire', 'english': 'drink', 'turkish': 'içki'},
    {'french': 'chien', 'english': 'chien', 'turkish': 'chien'},
    {'french': 'chat', 'english': 'chat', 'turkish': 'sohbet'},
    {'french': 'poisson', 'english': 'poisson', 'turkish': 'poisson'},
    {'french': 'oiseau', 'english': 'bird', 'turkish': 'kuş'},
    {'french': 'arbre', 'english': 'arbre', 'turkish': 'arbre'},
    {'french': 'fleur', 'english': 'flower', 'turkish': 'çiçek'},
    {'french': 'soleil', 'english': 'sun', 'turkish': 'güneş'},
    {'french': 'lune', 'english': 'moon', 'turkish': 'ay'},
    {'french': 'étoile', 'english': 'star', 'turkish': 'yıldız'},
    {'french': 'ciel', 'english': 'sky', 'turkish': 'gökyüzü'},
    {'french': 'nuage', 'english': 'cloud', 'turkish': 'bulut'},
    {'french': 'pluie', 'english': 'rain', 'turkish': 'yağmur'},
    {'french': 'neige', 'english': 'tilt', 'turkish': 'eğim'},
    {'french': 'vent', 'english': 'vent', 'turkish': 'havalandırma'},
    {'french': 'feu', 'english': 'feu', 'turkish': 'feu'},
    {'french': 'terre', 'english': 'earth', 'turkish': 'toprak'},
    {'french': 'montagne', 'english': 'mountains', 'turkish': 'dağlar'},
    {'french': 'rivière', 'english': 'river', 'turkish': 'nehir'},
    {'french': 'océan', 'english': 'ocean', 'turkish': 'okyanus'},
    {'french': 'forêt', 'english': 'forest', 'turkish': 'orman'},
    {'french': 'désert', 'english': 'desert', 'turkish': 'Çöl'},
    {'french': 'île', 'english': 'island', 'turkish': 'ada'},
    {'french': 'plage', 'english': 'beach', 'turkish': 'plaj'},
    {'french': 'route', 'english': 'route', 'turkish': 'rota'},
    {'french': 'rue', 'english': 'rue', 'turkish': 'rue'},
    {'french': 'maison', 'english': 'home', 'turkish': 'ev'},
    {'french': 'appartement', 'english': 'apartment', 'turkish': 'daire'},
    {'french': 'école', 'english': 'school', 'turkish': 'okul'},
    {'french': 'université', 'english': 'university', 'turkish': 'üniversite'},
    {'french': 'hôpital', 'english': 'hospital', 'turkish': 'Hastane'},
    {'french': 'restaurant', 'english': 'restaurant', 'turkish': 'restoran'},
    {'french': 'magasin', 'english': 'high', 'turkish': 'yüksek'},
    {'french': 'cinéma', 'english': 'cinema', 'turkish': 'sinema'},
    {'french': 'théâtre', 'english': 'theater', 'turkish': 'TİYATRO'},
    {'french': 'musée', 'english': 'museum', 'turkish': 'müze'},
    {'french': 'bibliothèque', 'english': 'library', 'turkish': 'kütüphane'},
    {'french': 'parc', 'english': 'park', 'turkish': 'park'},
    {'french': 'jardin', 'english': 'jardin', 'turkish': 'jardin'},
    {'french': 'zoo', 'english': 'zoo', 'turkish': 'hayvanat bahçesi'},
    {'french': 'ferme', 'english': 'ferme', 'turkish': 'ferme'},
    {'french': 'bureau', 'english': 'office', 'turkish': 'ofis'},
    {'french': 'usine', 'english': 'usine', 'turkish': 'usine'},
    {'french': 'banque', 'english': 'bank', 'turkish': 'banka'},
    {'french': 'église', 'english': 'church', 'turkish': 'KİLİSE'},
    {'french': 'mosquée', 'english': 'mosque', 'turkish': 'CAMİ'},
    {'french': 'temple', 'english': 'temple', 'turkish': 'tapınak'},
    {'french': 'aéroport', 'english': 'airport', 'turkish': 'havaalanı'},
    {'french': 'gare', 'english': 'station', 'turkish': 'istasyon'},
    {'french': 'port', 'english': 'port', 'turkish': 'Liman'},
    {'french': 'pont', 'english': 'punt', 'turkish': 'punt'},
    {'french': 'tour', 'english': 'tower', 'turkish': 'Kule'},
    {'french': 'château', 'english': 'château', 'turkish': 'kale'},
    {'french': 'palais', 'english': 'palais', 'turkish': 'palais'},
    {'french': 'statue', 'english': 'statue', 'turkish': 'heykel'},
    {'french': 'monument', 'english': 'monument', 'turkish': 'ANIT'},
    {'french': 'voiture', 'english': 'car', 'turkish': 'araba'},
    {'french': 'vélo', 'english': 'bike', 'turkish': 'Bisiklet'},
    {'french': 'bus', 'english': 'bus', 'turkish': 'otobüs'},
    {'french': 'train', 'english': 'train', 'turkish': 'Tren'},
    {'french': 'avion', 'english': 'avion', 'turkish': 'avion'},
    {'french': 'bateau', 'english': 'boat', 'turkish': 'tekne'},
    {'french': 'métro', 'english': 'metro', 'turkish': 'metro'},
    {'french': 'taxi', 'english': 'taxi', 'turkish': 'taksi'},
    {'french': 'moto', 'english': 'moto', 'turkish': 'Moto'},
    {'french': 'camion', 'english': 'camion', 'turkish': 'camion'},
    {'french': 'ordinateur', 'english': 'computer', 'turkish': 'bilgisayar'},
    {'french': 'téléphone', 'english': 'phone', 'turkish': 'Telefon'},
    {'french': 'télévision', 'english': 'television', 'turkish': 'televizyon'},
    {'french': 'radio', 'english': 'radio', 'turkish': 'radyo'},
    {'french': 'internet', 'english': 'Internet', 'turkish': 'İnternet'},
    {'french': 'livre', 'english': 'book', 'turkish': 'Kitap'},
    {'french': 'journal', 'english': 'diary', 'turkish': 'GÜNLÜK'},
    {'french': 'magazine', 'english': 'magazine', 'turkish': 'dergi'},
    {'french': 'lettre', 'english': 'letter', 'turkish': 'mektup'},
    {'french': 'stylo', 'english': 'stylo', 'turkish': 'stylo'},
    {'french': 'crayon', 'english': 'pencil', 'turkish': 'kalem'},
    {'french': 'papier', 'english': 'paper', 'turkish': 'Kağıt'},
    {'french': 'cahier', 'english': 'notebook', 'turkish': 'defter'},
    {'french': 'sac', 'english': 'sac', 'turkish': 'kese'},
    {'french': 'valise', 'english': 'cast', 'turkish': 'döküm'},
    {'french': 'clé', 'english': 'key', 'turkish': 'Anahtar'},
    {'french': 'montre', 'english': 'watch', 'turkish': 'İzle'},
    {'french': 'lunettes', 'english': 'glasses', 'turkish': 'Gözlükler'},
    {'french': 'chapeau', 'english': 'hat', 'turkish': 'Şapka'},
    {'french': 'chaussure', 'english': 'shoe', 'turkish': 'Ayakkabı'},
    {'french': 'vêtement', 'english': 'clothing', 'turkish': 'GİYİM'},
    {'french': 'pantalon', 'english': 'pantalon', 'turkish': 'pantalon'},
    {'french': 'chemise', 'english': 'chemise', 'turkish': 'chemise'},
    {'french': 'robe', 'english': 'robe', 'turkish': 'bornoz'},
    {'french': 'jupe', 'english': 'skirt', 'turkish': 'bkz.'},
    {'french': 'manteau', 'english': 'coat', 'turkish': 'ceket'},
    {'french': 'gant', 'english': 'gant', 'turkish': 'gant'},
    {'french': 'écharpe', 'english': 'scarf', 'turkish': 'eşarp'},
    {'french': 'cravate', 'english': 'cravate', 'turkish': 'cravate'},
    {'french': 'bijou', 'english': 'jewelry', 'turkish': 'mücevher'},
    {'french': 'pain', 'english': 'pain', 'turkish': 'ağrı'},
    {'french': 'fromage', 'english': 'fromage', 'turkish': 'fromage'},
    {'french': 'viande', 'english': 'viande', 'turkish': 'viande'},
    {'french': 'poisson', 'english': 'poisson', 'turkish': 'poisson'},
    {'french': 'légume', 'english': 'vegetable', 'turkish': 'sebze'},
    {'french': 'fruit', 'english': 'fruit', 'turkish': 'meyve'},
    {'french': 'riz', 'english': 'riz', 'turkish': 'riz'},
    {'french': 'pâte', 'english': 'paste', 'turkish': 'macun'},
    {'french': 'œuf', 'english': 'egg', 'turkish': 'yumurta'},
    {'french': 'lait', 'english': 'Laws', 'turkish': 'Kanunlar'},
    {'french': 'café', 'english': 'coffee', 'turkish': 'Kahve'},
    {'french': 'thé', 'english': 'tea', 'turkish': 'çay'},
    {'french': 'jus', 'english': 'jus', 'turkish': 'jus'},
    {'french': 'vin', 'english': 'vin', 'turkish': 'vin'},
    {'french': 'bière', 'english': 'beer', 'turkish': 'ayı'},
    {'french': 'eau', 'english': 'eau', 'turkish': 'Eau'},
    {'french': 'sucre', 'english': 'sugar', 'turkish': 'şeker'},
    {'french': 'sel', 'english': 'sel', 'turkish': 'sel'},
    {'french': 'huile', 'english': 'huile', 'turkish': 'huile'},
    {'french': 'sauce', 'english': 'sauce', 'turkish': 'sos'},
    {'french': 'soupe', 'english': 'soup', 'turkish': 'çorba'},
    {'french': 'salade', 'english': 'salad', 'turkish': 'salata'},
    {'french': 'dessert', 'english': 'dessert', 'turkish': 'tatlı'},
    {'french': 'gâteau', 'english': 'cake', 'turkish': 'KEK'},
    {'french': 'chocolat', 'english': 'chocolat', 'turkish': 'ÇİKOLATA'},
    {'french': 'bonbon', 'english': 'bonbon', 'turkish': 'bonbon'},
    {'french': 'glace', 'english': 'glace', 'turkish': 'glace'},
    {'french': 'miel', 'english': 'miel', 'turkish': 'miel'},
    {'french': 'confiture', 'english': 'jam', 'turkish': 'reçel'},
    {'french': 'beurre', 'english': 'beurre', 'turkish': 'beurre'},
    {'french': 'médecin', 'english': 'doctor', 'turkish': 'doktor'},
    {'french': 'infirmier', 'english': 'infirmier', 'turkish': 'infirmier'},
    {'french': 'avocat', 'english': 'lawyer', 'turkish': 'avukat'},
    {'french': 'juge', 'english': 'judge', 'turkish': 'yargıç'},
    {'french': 'policier', 'english': 'police officer', 'turkish': 'POLİS MEMURU'},
    {'french': 'pompier', 'english': 'pompier', 'turkish': 'pompier'},
    {'french': 'soldat', 'english': 'soldat', 'turkish': 'soldat'},
    {'french': 'professeur', 'english': 'professor', 'turkish': 'Profesör'},
    {'french': 'étudiant', 'english': 'student', 'turkish': 'öğrenci'},
    {'french': 'élève', 'english': 'student', 'turkish': 'öğrenci'},
    {'french': 'vendeur', 'english': 'vendeur', 'turkish': 'Vendeur'},
    {'french': 'client', 'english': 'customer', 'turkish': 'müşteri'},
    {'french': 'patron', 'english': 'pattern', 'turkish': 'desen'},
    {'french': 'employé', 'english': 'employee', 'turkish': 'çalışan'},
    {'french': 'ouvrier', 'english': 'worker', 'turkish': 'işçi'},
    {'french': 'agriculteur', 'english': 'farmer', 'turkish': 'ÇİFTÇİ'},
    {'french': 'pêcheur', 'english': 'fisherman', 'turkish': 'BALIKÇI'},
    {'french': 'artiste', 'english': 'artist', 'turkish': 'Sanatçı'},
    {'french': 'musicien', 'english': 'musicien', 'turkish': 'MÜZİSYEN'},
    {'french': 'acteur', 'english': 'actor', 'turkish': 'aktör'},
    {'french': 'chanteur', 'english': 'singer', 'turkish': 'şarkıcı'},
    {'french': 'danseur', 'english': 'dancer', 'turkish': 'dansçı'},
    {'french': 'peintre', 'english': 'painter', 'turkish': 'Ressam'},
    {'french': 'écrivain', 'english': 'writer', 'turkish': 'yazar'},
    {'french': 'journaliste', 'english': 'journalist', 'turkish': 'gazeteci'},
    {'french': 'photographe', 'english': 'photographer', 'turkish': 'fotoğrafçı'},
    {'french': 'scientifique', 'english': 'scientific', 'turkish': 'bilimsel'},
    {'french': 'ingénieur', 'english': 'engineer', 'turkish': 'mühendis'},
    {'french': 'architecte', 'english': 'architecte', 'turkish': 'architecte'},
    {'french': 'designer', 'english': 'designer', 'turkish': 'tasarımcı'},
    {'french': 'sport', 'english': 'sport', 'turkish': 'spor'},
    {'french': 'football', 'english': 'football', 'turkish': 'futbol'},
    {'french': 'tennis', 'english': 'tennis', 'turkish': 'Tenis'},
    {'french': 'basketball', 'english': 'basketball', 'turkish': 'Basketbol'},
    {'french': 'volleyball', 'english': 'volleyball', 'turkish': 'voleybol'},
    {'french': 'natation', 'english': 'natation', 'turkish': 'natasyon'},
    {'french': 'ski', 'english': 'ski', 'turkish': 'kayak'},
    {'french': 'golf', 'english': 'golf', 'turkish': 'golf'},
    {'french': 'boxe', 'english': 'boxe', 'turkish': 'boxe'},
    {'french': 'judo', 'english': 'judo', 'turkish': 'judo'},
    {'french': 'yoga', 'english': 'yoga', 'turkish': 'yoga'},
    {'french': 'danse', 'english': 'dance', 'turkish': 'Dans'},
    {'french': 'gymnastique', 'english': 'gymnastics', 'turkish': 'Jimnastik'},
    {'french': 'athlétisme', 'english': 'athletics', 'turkish': 'ATLETİZM'},
    {'french': 'course', 'english': 'race', 'turkish': 'yarış'},
    {'french': 'saut', 'english': 'jump', 'turkish': 'Zıpla'},
    {'french': 'lancer', 'english': 'launch', 'turkish': 'fırlatma'},
    {'french': 'équitation', 'english': 'riding', 'turkish': 'sürme'},
    {'french': 'voile', 'english': 'veil', 'turkish': 'Peçe'},
    {'french': 'plongée', 'english': 'diving', 'turkish': 'Dalış'},
    {'french': 'musique', 'english': 'music', 'turkish': 'müzik'},
    {'french': 'chanson', 'english': 'song', 'turkish': 'şarkı'},
    {'french': 'concert', 'english': 'concert', 'turkish': 'konser'},
    {'french': 'instrument', 'english': 'instrument', 'turkish': 'enstrüman'},
    {'french': 'guitare', 'english': 'guitare', 'turkish': 'guitare'},
    {'french': 'piano', 'english': 'plan', 'turkish': 'plan'},
    {'french': 'violon', 'english': 'violon', 'turkish': 'VİYOLON'},
    {'french': 'batterie', 'english': 'batterie', 'turkish': 'BATTERIE'},
    {'french': 'flûte', 'english': 'flute', 'turkish': 'Flüt'},
    {'french': 'trompette', 'english': 'trompette', 'turkish': 'trompette'},
    {'french': 'peinture', 'english': 'paint', 'turkish': 'boya'},
    {'french': 'sculpture', 'english': 'sculpture', 'turkish': 'heykel'},
    {'french': 'dessin', 'english': 'drawing', 'turkish': 'çizim'},
    {'french': 'photographie', 'english': 'photography', 'turkish': 'fotoğrafçılık'},
    {'french': 'cinéma', 'english': 'cinema', 'turkish': 'sinema'},
    {'french': 'film', 'english': 'film', 'turkish': 'Film'},
    {'french': 'acteur', 'english': 'actor', 'turkish': 'aktör'},
    {'french': 'réalisateur', 'english': 'director', 'turkish': 'Müdür'},
    {'french': 'scène', 'english': 'scene', 'turkish': 'sahne'},
    {'french': 'caméra', 'english': 'camera', 'turkish': 'Kamera'},
    {'french': 'animal', 'english': 'animal', 'turkish': 'hayvan'},
    {'french': 'mammifère', 'english': 'mammal', 'turkish': 'memeli'},
    {'french': 'oiseau', 'english': 'bird', 'turkish': 'kuş'},
    {'french': 'poisson', 'english': 'poisson', 'turkish': 'poisson'},
    {'french': 'reptile', 'english': 'reptile', 'turkish': 'sürüngen'},
    {'french': 'amphibien', 'english': 'amphibian', 'turkish': 'amfibi'},
    {'french': 'insecte', 'english': 'insect', 'turkish': 'böcek'},
    {'french': 'araignée', 'english': 'spider', 'turkish': 'örümcek'},
    {'french': 'ver', 'english': 'ver', 'turkish': 'ver'},
    {'french': 'bactérie', 'english': 'bacteria', 'turkish': 'bakteriler'},
    {'french': 'lion', 'english': 'lion', 'turkish': 'ASLAN'},
    {'french': 'tigre', 'english': 'tigre', 'turkish': 'tigre'},
    {'french': 'éléphant', 'english': 'elephant', 'turkish': 'FİL'},
    {'french': 'girafe', 'english': 'giraffe', 'turkish': 'ZÜRAFA'},
    {'french': 'singe', 'english': 'singe', 'turkish': 'TEK'},
    {'french': 'ours', 'english': 'bears', 'turkish': 'ayılar'},
    {'french': 'loup', 'english': 'wolf', 'turkish': 'kurt'},
    {'french': 'renard', 'english': 'renard', 'turkish': 'renard'},
    {'french': 'cerf', 'english': 'deer', 'turkish': 'geyik'},
    {'french': 'lapin', 'english': 'Lapland', 'turkish': 'Lapland'},
    {'french': 'aigle', 'english': 'aigle', 'turkish': 'aigle'},
    {'french': 'hibou', 'english': 'hibou', 'turkish': 'hibou'},
    {'french': 'perroquet', 'english': 'perroquet', 'turkish': 'perroquet'},
    {'french': 'pingouin', 'english': 'penguin', 'turkish': 'penguen'},
    {'french': 'mouette', 'english': 'seagull', 'turkish': 'martı'},
    {'french': 'corbeau', 'english': 'raven', 'turkish': 'Kuzgun'},
    {'french': 'canard', 'english': 'canard', 'turkish': 'canard'},
    {'french': 'poule', 'english': 'hen', 'turkish': 'hen'},
    {'french': 'coq', 'english': 'coq', 'turkish': 'coq'},
    {'french': 'pigeon', 'english': 'pigeon', 'turkish': 'güvercin'},
    {'french': 'requin', 'english': 'requin', 'turkish': 'requin'},
    {'french': 'baleine', 'english': 'baleine', 'turkish': 'baleine'},
    {'french': 'dauphin', 'english': 'dolphin', 'turkish': 'YUNUS'},
    {'french': 'pieuvre', 'english': 'octopus', 'turkish': 'Ahtapot'},
    {'french': 'crabe', 'english': 'crab', 'turkish': 'yengeç'},
    {'french': 'homard', 'english': 'lobster', 'turkish': 'Istakoz'},
    {'french': 'crevette', 'english': 'shrimp', 'turkish': 'karides'},
    {'french': 'moule', 'english': 'mold', 'turkish': 'Küf'},
    {'french': 'huître', 'english': 'oyster', 'turkish': 'istiridye'},
    {'french': 'escargot', 'english': 'escargot', 'turkish': 'salyangoz'},
    {'french': 'serpent', 'english': 'serpent', 'turkish': 'Yılan'},
    {'french': 'lézard', 'english': 'lizard', 'turkish': 'kertenkele'},
    {'french': 'crocodile', 'english': 'crocodile', 'turkish': 'timsah'},
    {'french': 'tortue', 'english': 'tortue', 'turkish': 'tortue'},
    {'french': 'grenouille', 'english': 'frog', 'turkish': 'kurbağa'},
    {'french': 'crapaud', 'english': 'crapaud', 'turkish': 'crapaud'},
    {'french': 'salamandre', 'english': 'salamandre', 'turkish': 'salamandre'},
    {'french': 'triton', 'english': 'triton', 'turkish': 'triton'},
    {'french': 'axolotl', 'english': 'axolotl', 'turkish': 'axolotl'},
    {'french': 'caméléon', 'english': 'chameleon', 'turkish': 'bukalemun'},
    {'french': 'abeille', 'english': 'bee', 'turkish': 'Arı'},
    {'french': 'fourmi', 'english': 'ant', 'turkish': 'karınca'},
    {'french': 'mouche', 'english': 'fly', 'turkish': 'uçmak'},
    {'french': 'moustique', 'english': 'mosquito', 'turkish': 'sivrisinek'},
    {'french': 'papillon', 'english': 'papillon', 'turkish': 'papillon'},
    {'french': 'coccinelle', 'english': 'ladybugs', 'turkish': 'uğur böcekleri'},
    {'french': 'scarabée', 'english': 'beetle', 'turkish': 'böcek'},
    {'french': 'libellule', 'english': 'dragonflies', 'turkish': 'yusufçuk'},
    {'french': 'mante', 'english': 'mante', 'turkish': 'Mante'},
    {'french': 'phasme', 'english': 'phasme', 'turkish': 'phasme'},
    {'french': 'corps', 'english': 'body', 'turkish': 'vücut'},
    {'french': 'tête', 'english': 'head', 'turkish': 'Kafa'},
    {'french': 'cou', 'english': 'cou', 'turkish': 'cou'},
    {'french': 'épaule', 'english': 'shoulder', 'turkish': 'Omuz'},
    {'french': 'bras', 'english': 'bras', 'turkish': 'Sütyenler'},
    {'french': 'coude', 'english': 'coude', 'turkish': 'Coude'},
    {'french': 'poignet', 'english': 'wrist', 'turkish': 'bilek'},
    {'french': 'main', 'english': 'main', 'turkish': 'ana'},
    {'french': 'doigt', 'english': 'finger', 'turkish': 'parmak'},
    {'french': 'ongle', 'english': 'ongle', 'turkish': 'ongle'},
    {'french': 'jambe', 'english': 'leg', 'turkish': 'bacak'},
    {'french': 'genou', 'english': 'genou', 'turkish': 'genou'},
    {'french': 'cheville', 'english': 'ankle', 'turkish': 'ayak bileği'},
    {'french': 'pied', 'english': 'pied', 'turkish': 'alaca'},
    {'french': 'orteil', 'english': 'advantage', 'turkish': 'avantaj'},
    {'french': 'dos', 'english': 'dos', 'turkish': 'dos'},
    {'french': 'ventre', 'english': 'belly', 'turkish': 'göbek'},
    {'french': 'poitrine', 'english': 'chest', 'turkish': 'göğüs'},
    {'french': 'cœur', 'english': 'heart', 'turkish': 'kalp'},
    {'french': 'poumon', 'english': 'lung', 'turkish': 'çözüm'},
    {'french': 'cerveau', 'english': 'brain', 'turkish': 'Beyin'},
    {'french': 'estomac', 'english': 'estomac', 'turkish': 'estomac'},
    {'french': 'foie', 'english': 'liver', 'turkish': 'Karaciğer'},
    {'french': 'rein', 'english': 'pure', 'turkish': 'saf'},
    {'french': 'intestin', 'english': 'intestin', 'turkish': 'bağırsak'},
    {'french': 'muscle', 'english': 'muscle', 'turkish': 'kas'},
    {'french': 'os', 'english': 'os', 'turkish': 'os'},
    {'french': 'peau', 'english': 'skin', 'turkish': 'cilt'},
    {'french': 'cheveu', 'english': 'hair', 'turkish': 'saç'},
    {'french': 'barbe', 'english': 'beard', 'turkish': 'sakal'},
    {'french': 'œil', 'english': 'eye', 'turkish': 'göz'},
    {'french': 'nez', 'english': 'nez', 'turkish': 'nez'},
    {'french': 'bouche', 'english': 'mouth', 'turkish': 'ağız'},
    {'french': 'oreille', 'english': 'oreille', 'turkish': 'oreille'},
    {'french': 'dent', 'english': 'dent', 'turkish': 'DİŞ'},
    {'french': 'langue', 'english': 'language', 'turkish': 'DİL'},
    {'french': 'lèvre', 'english': 'lip', 'turkish': 'dudak'},
    {'french': 'joue', 'english': 'play', 'turkish': 'Oyna'},
    {'french': 'menton', 'english': 'chin', 'turkish': 'Çene'},
    {'french': 'front', 'english': 'front', 'turkish': 'ön'},
    {'french': 'couleur', 'english': 'color', 'turkish': 'renk'},
    {'french': 'rouge', 'english': 'red', 'turkish': 'kırmızı'},
    {'french': 'bleu', 'english': 'blue', 'turkish': 'mavi'},
    {'french': 'vert', 'english': 'vert', 'turkish': 'vert'},
    {'french': 'jaune', 'english': 'young', 'turkish': 'genç'},
    {'french': 'orange', 'english': 'orange', 'turkish': 'turuncu'},
    {'french': 'violet', 'english': 'violet', 'turkish': 'menekşe'},
    {'french': 'rose', 'english': 'rose', 'turkish': 'gül'},
    {'french': 'marron', 'english': 'marron', 'turkish': 'marron'},
    {'french': 'gris', 'english': 'gris', 'turkish': 'gris'},
    {'french': 'blanc', 'english': 'white', 'turkish': 'beyaz'},
    {'french': 'noir', 'english': 'black', 'turkish': 'siyah'},
    {'french': 'clair', 'english': 'clear', 'turkish': 'temiz'},
    {'french': 'foncé', 'english': 'dark', 'turkish': 'karanlık'},
    {'french': 'brillant', 'english': 'brillant', 'turkish': 'brillant'},
    {'french': 'mat', 'english': 'mat', 'turkish': 'mat'},
    {'french': 'transparent', 'english': 'transparent', 'turkish': 'şeffaf'},
    {'french': 'opaque', 'english': 'opaque', 'turkish': 'opak'},
    {'french': 'arc-en-ciel', 'english': 'rainbow', 'turkish': 'gökkuşağı'},
    {'french': 'nuance', 'english': 'nuance', 'turkish': 'nüans'},
    {'french': 'forme', 'english': 'forme', 'turkish': 'forme'},
    {'french': 'carré', 'english': 'square', 'turkish': 'kare'},
    {'french': 'rectangle', 'english': 'rectangle', 'turkish': 'dikdörtgen'},
    {'french': 'triangle', 'english': 'triangle', 'turkish': 'üçgen'},
    {'french': 'cercle', 'english': 'circle', 'turkish': 'daire'},
    {'french': 'ovale', 'english': 'ovals', 'turkish': 'Ovaller'},
    {'french': 'losange', 'english': 'lozenge', 'turkish': 'pastil'},
    {'french': 'étoile', 'english': 'star', 'turkish': 'yıldız'},
    {'french': 'cœur', 'english': 'heart', 'turkish': 'kalp'},
    {'french': 'flèche', 'english': 'arrow', 'turkish': 'ok'},
    {'french': 'ligne', 'english': 'line', 'turkish': 'hat'},
    {'french': 'courbe', 'english': 'curve', 'turkish': 'Eğri'},
    {'french': 'angle', 'english': 'angle', 'turkish': 'açı'},
    {'french': 'point', 'english': 'point', 'turkish': 'nokta'},
    {'french': 'surface', 'english': 'surface', 'turkish': 'yüzey'},
    {'french': 'volume', 'english': 'volume', 'turkish': 'hacim'},
    {'french': 'dimension', 'english': 'dimension', 'turkish': 'boyut'},
    {'french': 'taille', 'english': 'size', 'turkish': 'boyut'},
    {'french': 'poids', 'english': 'poids', 'turkish': 'poids'},
    {'french': 'masse', 'english': 'masses', 'turkish': 'kitleler'},
    {'french': 'longueur', 'english': 'length', 'turkish': 'uzunluk'},
    {'french': 'largeur', 'english': 'width', 'turkish': 'genişlik'},
    {'french': 'hauteur', 'english': 'height', 'turkish': 'yükseklik'},
    {'french': 'profondeur', 'english': 'depth', 'turkish': 'derinlik'},
    {'french': 'distance', 'english': 'distance', 'turkish': 'mesafe'},
    {'french': 'vitesse', 'english': 'speed', 'turkish': 'hız'},
    {'french': 'accélération', 'english': 'acceleration', 'turkish': 'hızlanma'},
    {'french': 'force', 'english': 'force', 'turkish': 'kuvvet'},
    {'french': 'énergie', 'english': 'énergie', 'turkish': 'énergie'},
    {'french': 'puissance', 'english': 'power', 'turkish': 'güç'},
    {'french': 'chaleur', 'english': 'heat', 'turkish': 'ısı'},
    {'french': 'froid', 'english': 'cold', 'turkish': 'soğuk'},
    {'french': 'température', 'english': 'temperature', 'turkish': 'sıcaklık'},
    {'french': 'pression', 'english': 'pression', 'turkish': 'BASINÇ'},
    {'french': 'densité', 'english': 'density', 'turkish': 'yoğunluk'},
    {'french': 'gravité', 'english': 'gravité', 'turkish': 'gravité'},
    {'french': 'friction', 'english': 'friction', 'turkish': 'Sürtünme'},
    {'french': 'équilibre', 'english': 'balance', 'turkish': 'denge'},
    {'french': 'mouvement', 'english': 'movement', 'turkish': 'hareket'},
    {'french': 'repos', 'english': 'repos', 'turkish': 'repolar'},
    {'french': 'espace', 'english': 'espace', 'turkish': 'espace'},
    {'french': 'temps', 'english': 'time', 'turkish': 'zaman'},
    {'french': 'durée', 'english': 'duration', 'turkish': 'süre'},
    {'french': 'instant', 'english': 'instant', 'turkish': 'anında'},
    {'french': 'période', 'english': 'period', 'turkish': 'dönem'},
    {'french': 'cycle', 'english': 'cycle', 'turkish': 'döngü'},
    {'french': 'rythme', 'english': 'rhythm', 'turkish': 'Ritim'},
    {'french': 'fréquence', 'english': 'frequency', 'turkish': 'frekans'},
    {'french': 'passé', 'english': 'past', 'turkish': 'geçmiş'},
    {'french': 'présent', 'english': 'present', 'turkish': 'Mevcut'},
    {'french': 'futur', 'english': 'futur', 'turkish': 'gelecek'},
    {'french': 'hier', 'english': 'here', 'turkish': 'Burada'},
    {'french': "aujourd'hui", 'english': 'today', 'turkish': 'bugün'},
    {'french': 'demain', 'english': 'demain', 'turkish': 'demain'},
    {'french': 'matin', 'english': 'matin', 'turkish': 'matin'},
    {'french': 'midi', 'english': 'midi', 'turkish': 'midi'},
    {'french': 'soir', 'english': 'evening', 'turkish': 'Akşam'},
    {'french': 'nuit', 'english': 'nuit', 'turkish': 'Nuit'},
    {'french': 'aube', 'english': 'aube', 'turkish': 'aube'},
    {'french': 'crépuscule', 'english': 'twilight', 'turkish': 'alacakaranlık'},
    {'french': 'heure', 'english': 'hour', 'turkish': 'saat'},
    {'french': 'minute', 'english': 'minute', 'turkish': 'dakika'},
    {'french': 'seconde', 'english': 'second', 'turkish': 'ikinci'},
    {'french': 'jour', 'english': 'day', 'turkish': 'gün'},
    {'french': 'semaine', 'english': 'semaine', 'turkish': 'semaine'},
    {'french': 'mois', 'english': 'month', 'turkish': 'ay'},
    {'french': 'année', 'english': 'year', 'turkish': 'yıl'},
    {'french': 'siècle', 'english': 'century', 'turkish': 'yüzyıl'},
    {'french': 'millénaire', 'english': 'millennium', 'turkish': 'milenyum'},
    {'french': 'ère', 'english': 'era', 'turkish': 'dönem'},
    {'french': 'saison', 'english': 'season', 'turkish': 'sezon'},
    {'french': 'printemps', 'english': 'spring', 'turkish': 'bahar'},
    {'french': 'été', 'english': 'summer', 'turkish': 'yaz'},
    {'french': 'automne', 'english': 'automne', 'turkish': 'automne'},
    {'french': 'hiver', 'english': 'hiver', 'turkish': 'Hiver'},
    {'french': 'climat', 'english': 'climat', 'turkish': 'iklim'},
    {'french': 'météo', 'english': 'weather', 'turkish': 'hava durumu'},
    {'french': 'orage', 'english': 'orage', 'turkish': 'orage'},
    {'french': 'tempête', 'english': 'storm', 'turkish': 'Fırtına'},
    {'french': 'ouragan', 'english': 'ouragan', 'turkish': 'ouragan'},
    {'french': 'typhon', 'english': 'typhon', 'turkish': 'typhon'},
    {'french': 'tornade', 'english': 'tornado', 'turkish': 'kasırga'},
    {'french': 'tsunami', 'english': 'tsunami', 'turkish': 'Tsunami'},
    {'french': 'séisme', 'english': 'earthquake', 'turkish': 'DEPREM'},
    {'french': 'volcan', 'english': 'volcan', 'turkish': 'volkan'},
    {'french': 'éruption', 'english': 'rash', 'turkish': 'kızarıklık'},
    {'french': 'avalanche', 'english': 'avalanche', 'turkish': 'ÇIĞ'},
    {'french': 'inondation', 'english': 'flood', 'turkish': 'sel'},
    {'french': 'sécheresse', 'english': 'drought', 'turkish': 'Kuraklık'},
    {'french': 'canicule', 'english': 'canicule', 'turkish': 'canicule'},
    {'french': 'nord', 'english': 'North', 'turkish': 'Kuzey'},
    {'french': 'sud', 'english': 'sud', 'turkish': 'sud'},
    {'french': 'est', 'english': 'est', 'turkish': 'est'},
    {'french': 'ouest', 'english': 'west', 'turkish': 'Batı'},
    {'french': 'direction', 'english': 'direction', 'turkish': 'yön'},
    {'french': 'orientation', 'english': 'orientation', 'turkish': 'oryantasyon'},
    {'french': 'boussole', 'english': 'boussole', 'turkish': 'Boussole'},
    {'french': 'carte', 'english': 'cards', 'turkish': 'kartlar'},
    {'french': 'globe', 'english': 'globe', 'turkish': 'Küre'},
    {'french': 'atlas', 'english': 'atlas', 'turkish': 'atlas'},
    {'french': 'continent', 'english': 'continent', 'turkish': 'kıta'},
    {'french': 'pays', 'english': 'country', 'turkish': 'ülke'},
    {'french': 'région', 'english': 'region', 'turkish': 'bölge'},
    {'french': 'département', 'english': 'department', 'turkish': 'departman'},
    {'french': 'ville', 'english': 'city', 'turkish': 'ŞEHİR'},
    {'french': 'village', 'english': 'village', 'turkish': 'KÖY'},
    {'french': 'quartier', 'english': 'district', 'turkish': 'bölge'},
    {'french': 'rue', 'english': 'rue', 'turkish': 'rue'},
    {'french': 'avenue', 'english': 'avenue', 'turkish': 'CADDE'},
    {'french': 'boulevard', 'english': 'boulevard', 'turkish': 'BULVAR'},
    {'french': 'place', 'english': 'place', 'turkish': 'yer'},
    {'french': 'carrefour', 'english': 'carrefour', 'turkish': 'carrefour'},
    {'french': 'impasse', 'english': 'impasse', 'turkish': 'çıkmaz'},
    {'french': 'ruelle', 'english': 'alley', 'turkish': 'sokak'},
    {'french': 'chemin', 'english': 'chemin', 'turkish': 'chemin'},
    {'french': 'sentier', 'english': 'path', 'turkish': 'yol'},
    {'french': 'piste', 'english': 'Point', 'turkish': 'Nokta'},
    {'french': 'autoroute', 'english': 'autoroute', 'turkish': 'autoroute'},
    {'french': 'péage', 'english': 'toll', 'turkish': 'ücretli'},
    {'french': 'aire', 'english': 'area', 'turkish': 'alan'},
    {'french': 'frontière', 'english': 'border', 'turkish': 'sınır'},
    {'french': 'douane', 'english': 'customs', 'turkish': 'gümrükler'},
    {'french': 'passeport', 'english': 'passport', 'turkish': 'pasaport'},
    {'french': 'visa', 'english': 'visas', 'turkish': 'gösterilen'},
    {'french': 'nationalité', 'english': 'nationality', 'turkish': 'UYRUK'},
    {'french': 'citoyenneté', 'english': 'citizenship', 'turkish': 'vatandaşlık'},
    {'french': 'identité', 'english': 'identity', 'turkish': 'kimlik'},
    {'french': 'origine', 'english': 'origine', 'turkish': 'köken'},
    {'french': 'culture', 'english': 'culture', 'turkish': 'kültür'},
    {'french': 'tradition', 'english': 'tradition', 'turkish': 'gelenek'},
    {'french': 'coutume', 'english': 'custom', 'turkish': 'özel'},
    {'french': 'fête', 'english': 'party', 'turkish': 'parti'},
    {'french': 'célébration', 'english': 'celebration', 'turkish': 'kutlama'},
    {'french': 'cérémonie', 'english': 'ceremony', 'turkish': 'tören'},
    {'french': 'rituel', 'english': 'ritual', 'turkish': 'ritüel'},
    {'french': 'religion', 'english': 'religion', 'turkish': 'DİN'},
    {'french': 'spiritualité', 'english': 'spiritualité', 'turkish': 'spiritualité'},
    {'french': 'croyance', 'english': 'belief', 'turkish': 'inanç'},
    {'french': 'foi', 'english': 'foi', 'turkish': 'foi'},
    {'french': 'mythe', 'english': 'myth', 'turkish': 'efsane'},
    {'french': 'légende', 'english': 'air end', 'turkish': 'hava ucu'},
    {'french': 'conte', 'english': 'conte', 'turkish': 'conte'},
    {'french': 'fable', 'english': 'fable', 'turkish': 'masal'},
    {'french': 'histoire', 'english': 'history', 'turkish': 'TARİH'},
    {'french': 'récit', 'english': 'story', 'turkish': 'hikaye'},
    {'french': 'roman', 'english': 'novel', 'turkish': 'roman'},
    {'french': 'nouvelle', 'english': 'new', 'turkish': 'yeni'},
    {'french': 'poème', 'english': 'poem', 'turkish': 'ŞİİR'},
    {'french': 'vers', 'english': 'vers', 'turkish': 'vers'},
    {'french': 'rime', 'english': 'rime', 'turkish': 'Rime'},
    {'french': 'littérature', 'english': 'literature', 'turkish': 'Edebiyat'},
    {'french': 'grammaire', 'english': 'grammar', 'turkish': 'gramer'},
    {'french': 'vocabulaire', 'english': 'vocabulary', 'turkish': 'kelime hazinesi'},
    {'french': 'syntaxe', 'english': 'syntax', 'turkish': 'sözdizimi'},
    {'french': 'phrase', 'english': 'phrase', 'turkish': 'İfade'},
    {'french': 'mot', 'english': 'mot', 'turkish': 'mot'},
    {'french': 'syllabe', 'english': 'syllable', 'turkish': 'hece'},
    {'french': 'lettre', 'english': 'letter', 'turkish': 'mektup'},
    {'french': 'accent', 'english': 'accent', 'turkish': 'aksan'},
    {'french': 'ponctuation', 'english': 'punctuation', 'turkish': 'noktalama işaretleri'},
    {'french': 'langue', 'english': 'language', 'turkish': 'DİL'},
    {'french': 'dialecte', 'english': 'dialect', 'turkish': 'lehçe'},
    {'french': 'accent', 'english': 'accent', 'turkish': 'aksan'},
    {'french': 'prononciation', 'english': 'pronunciation', 'turkish': 'telaffuz'},
    {'french': 'intonation', 'english': 'intonation', 'turkish': 'tonlama'},
    {'french': 'conversation', 'english': 'conversation', 'turkish': 'konuşma'},
    {'french': 'dialogue', 'english': 'dialogue', 'turkish': 'DİYALOG'},
    {'french': 'monologue', 'english': 'monologue', 'turkish': 'monolog'},
    {'french': 'discours', 'english': 'speech', 'turkish': 'konuşma'},
    {'french': 'débat', 'english': 'debate', 'turkish': 'tartışma'},
    {'french': 'argument', 'english': 'argument', 'turkish': 'argüman'},
    {'french': 'opinion', 'english': 'opinion', 'turkish': 'görüş'},
    {'french': 'idée', 'english': 'idea', 'turkish': 'fikir'},
    {'french': 'pensée', 'english': 'thinking', 'turkish': 'düşünmek'},
    {'french': 'réflexion', 'english': 'reflection', 'turkish': 'yansıma'},
    {'french': 'imagination', 'english': 'imagination', 'turkish': 'hayal gücü'},
    {'french': 'créativité', 'english': 'creativity', 'turkish': 'yaratıcılık'},
    {'french': 'innovation', 'english': 'innovation', 'turkish': 'YENİLİK'},
    {'french': 'invention', 'english': 'invention', 'turkish': 'buluş'},
    {'french': 'découverte', 'english': 'discovery', 'turkish': 'keşif'},
    {'french': 'science', 'english': 'science', 'turkish': 'Bilim'},
    {'french': 'théorie', 'english': 'theory', 'turkish': 'teori'},
    {'french': 'hypothèse', 'english': 'hypothesis', 'turkish': 'hipotez'},
    {'french': 'expérience', 'english': 'experience', 'turkish': 'deneyim'},
    {'french': 'observation', 'english': 'observation', 'turkish': 'Gözlem'},
    {'french': 'analyse', 'english': 'analysis', 'turkish': 'ANALİZ'},
    {'french': 'synthèse', 'english': 'summary', 'turkish': 'özet'},
    {'french': 'conclusion', 'english': 'conclusion', 'turkish': 'Sonuç'},
    {'french': 'résultat', 'english': 'result', 'turkish': 'Sonuç'},
    {'french': 'preuve', 'english': 'proof', 'turkish': 'kanıt'},
    {'french': 'mathématiques', 'english': 'mathematics', 'turkish': 'matemati̇k'},
    {'french': 'calcul', 'english': 'calcul', 'turkish': 'hesaplamak'},
    {'french': 'algèbre', 'english': 'algebra', 'turkish': 'cebir'},
    {'french': 'géométrie', 'english': 'geometry', 'turkish': 'geometri'},
    {'french': 'statistique', 'english': 'statistics', 'turkish': 'istatistikler'},
    {'french': 'probabilité', 'english': 'probabilité', 'turkish': 'olasılık'},
    {'french': 'logique', 'english': 'logic', 'turkish': 'mantık'},
    {'french': 'raisonnement', 'english': 'reasoning', 'turkish': 'muhakeme'},
    {'french': 'problème', 'english': 'problem', 'turkish': 'problem'},
    {'french': 'solution', 'english': 'solution', 'turkish': 'çözüm'},
    {'french': 'physique', 'english': 'physics', 'turkish': 'FİZİK'},
    {'french': 'chimie', 'english': 'chemistry', 'turkish': 'KİMYA'},
    {'french': 'biologie', 'english': 'biology', 'turkish': 'BİYOLOJİ'},
    {'french': 'géologie', 'english': 'geology', 'turkish': 'jeoloji'},
    {'french': 'astronomie', 'english': 'astronomies', 'turkish': 'astronomi̇ler'},
    {'french': 'écologie', 'english': 'ecology', 'turkish': 'ekoloji'},
    {'french': 'météorologie', 'english': 'meteorology', 'turkish': 'meteoroloji'},
    {'french': 'océanographie', 'english': 'oceanography', 'turkish': 'oşinografi'},
    {'french': 'archéologie', 'english': 'archaeology', 'turkish': 'ARKEOLOJİ'},
    {'french': 'paléontologie', 'english': 'paleontology', 'turkish': 'paleontoloji'},
    {'french': 'médecine', 'english': 'medicine', 'turkish': 'tıp'},
    {'french': 'anatomie', 'english': 'anatomies', 'turkish': 'ANATOMİLER'},
    {'french': 'physiologie', 'english': 'physiology', 'turkish': 'FİZYOLOJİ'},
    {'french': 'pathologie', 'english': 'pathology', 'turkish': 'PATOLOJİ'},
    {'french': 'diagnostic', 'english': 'diagnostic', 'turkish': 'tanısal'},
    {'french': 'traitement', 'english': 'treatment', 'turkish': 'tedavi'},
    {'french': 'thérapie', 'english': 'therapy', 'turkish': 'TERAPİ'},
    {'french': 'chirurgie', 'english': 'Surgery', 'turkish': 'Ameliyat'},
    {'french': 'pharmacie', 'english': 'pharmacie', 'turkish': 'eczane'},
    {'french': 'vaccination', 'english': 'vaccination', 'turkish': 'aşılama'},
    {'french': 'psychologie', 'english': 'psychology', 'turkish': 'PSİKOLOJİ'},
    {'french': 'comportement', 'english': 'behavior', 'turkish': 'davranış'},
    {'french': 'émotion', 'english': 'emotion', 'turkish': 'duygu'},
    {'french': 'sentiment', 'english': 'sentiment', 'turkish': 'duyarlılık'},
    {'french': 'perception', 'english': 'perception', 'turkish': 'ALGI'},
    {'french': 'mémoire', 'english': 'memory', 'turkish': 'bellek'},
    {'french': 'apprentissage', 'english': 'learning', 'turkish': 'öğrenme'},
    {'french': 'intelligence', 'english': 'intelligence', 'turkish': 'Zeka'},
    {'french': 'personnalité', 'english': 'personality', 'turkish': 'kişilik'},
    {'french': 'conscience', 'english': 'awareness', 'turkish': 'farkındalık'},
    {'french': 'sociologie', 'english': 'sociology', 'turkish': 'Sosyoloji'},
    {'french': 'société', 'english': 'company', 'turkish': 'şirket'},
    {'french': 'groupe', 'english': 'group', 'turkish': 'Grup'},
    {'french': 'communauté', 'english': 'community', 'turkish': 'topluluk'},
    {'french': 'organisation', 'english': 'organization', 'turkish': 'organizasyon'},
    {'french': 'institution', 'english': 'institution', 'turkish': 'kurum'},
    {'french': 'gouvernement', 'english': 'government', 'turkish': 'hükümet'},
    {'french': 'loi', 'english': 'loi', 'turkish': 'loi'},
    {'french': 'justice', 'english': 'justice', 'turkish': 'adalet'},
    {'french': 'droit', 'english': 'right', 'turkish': 'doğru'},
    {'french': 'économie', 'english': 'economy', 'turkish': 'Ekonomi'},
    {'french': 'marché', 'english': 'market', 'turkish': 'Pazar'},
    {'french': 'entreprise', 'english': 'company', 'turkish': 'şirket'},
    {'french': 'commerce', 'english': 'trade', 'turkish': 'TİCARET'},
    {'french': 'industrie', 'english': 'industrie', 'turkish': 'endüstri'},
    {'french': 'agriculture', 'english': 'agriculture', 'turkish': 'TARIM'},
    {'french': 'finance', 'english': 'finance', 'turkish': 'Finans'},
    {'french': 'monnaie', 'english': 'currency', 'turkish': 'para birimi'},
    {'french': 'budget', 'english': 'budget', 'turkish': 'BÜTÇE'},
    {'french': 'investissement', 'english': 'investment', 'turkish': 'yatırım'},
    {'french': 'politique', 'english': 'policy', 'turkish': 'Politika'},
    {'french': 'démocratie', 'english': 'democracy', 'turkish': 'DEMOKRASİ'},
    {'french': 'république', 'english': 'republic', 'turkish': 'CUMHURİYET'},
    {'french': 'monarchie', 'english': 'monarchie', 'turkish': 'monarşi'},
    {'french': 'dictature', 'english': 'dictature', 'turkish': 'DİKTATÜR'},
    {'french': 'élection', 'english': 'election', 'turkish': 'seçim'},
    {'french': 'vote', 'english': 'vote', 'turkish': 'oylama'},
    {'french': 'parti', 'english': 'party', 'turkish': 'parti'},
    {'french': 'parlement', 'english': 'parliament', 'turkish': 'PARLAMENTO'},
    {'french': 'constitution', 'english': 'constitution', 'turkish': 'Anayasa'},
    {'french': 'diplomatie', 'english': 'diplomacy', 'turkish': 'DİPLOMASİ'},
    {'french': 'alliance', 'english': 'alliance', 'turkish': 'ittifak'},
    {'french': 'conflit', 'english': 'conflit', 'turkish': 'çatışma'},
    {'french': 'guerre', 'english': 'war', 'turkish': 'Savaş'},
    {'french': 'paix', 'english': 'peace', 'turkish': 'Barış'},
    {'french': 'négociation', 'english': 'negotiation', 'turkish': 'müzakere'},
    {'french': 'accord', 'english': 'accord', 'turkish': 'uyum'},
    {'french': 'traité', 'english': 'treaty', 'turkish': 'antlaşma'},
    {'french': 'convention', 'english': 'convention', 'turkish': 'KONGRE'},
    {'french': 'protocole', 'english': 'protocol', 'turkish': 'protokol'},
    {'french': 'environnement', 'english': 'environment', 'turkish': 'çevre'},
    {'french': 'nature', 'english': 'nature', 'turkish': 'doğa'},
    {'french': 'écosystème', 'english': 'ecosystem', 'turkish': 'ekosistem'},
    {'french': 'biodiversité', 'english': 'biodiversity', 'turkish': 'biyoçeşitlilik'},
    {'french': 'pollution', 'english': 'pollution', 'turkish': 'Kirlilik'},
    {'french': 'recyclage', 'english': 'recycling', 'turkish': 'geri dönüşüm'},
    {'french': 'développement durable', 'english': 'sustainable development', 'turkish': 'sürdürülebi̇li̇r kalkinma'},
    {'french': 'énergie renouvelable', 'english': 'renewable energy', 'turkish': 'yenilenebilir enerji'},
    {'french': 'conservation', 'english': 'conservation', 'turkish': 'koruma'},
    {'french': 'protection', 'english': 'protection', 'turkish': 'koruma'},
    {'french': 'technologie', 'english': 'technologies', 'turkish': 'teknolojiler'},
    {'french': 'innovation', 'english': 'innovation', 'turkish': 'YENİLİK'},
    {'french': 'progrès', 'english': 'progress', 'turkish': 'ilerleme'},
    {'french': 'évolution', 'english': 'evolution', 'turkish': 'EVRİM'},
    {'french': 'révolution', 'english': 'revolution', 'turkish': 'DEVRİM'},
    {'french': 'intelligence artificielle', 'english': 'artificial intelligence', 'turkish': 'yapay zeka'},
    {'french': 'robotique', 'english': 'robotics', 'turkish': 'robotik'},
    {'french': 'nanotechnologie', 'english': 'nanotechnologie', 'turkish': 'nanoteknoloji'},
    {'french': 'biotechnologie', 'english': 'biotechnologie', 'turkish': 'bi̇yoteknoloji̇'},
    {'french': 'génétique', 'english': 'genetics', 'turkish': 'GENETİK'},
    {'french': 'informatique', 'english': 'IT', 'turkish': 'IT'},
    {'french': 'logiciel', 'english': 'software', 'turkish': 'yazılım'},
    {'french': 'matériel', 'english': 'equipment', 'turkish': 'Ekipman'},
    {'french': 'réseau', 'english': 'network', 'turkish': 'ağ'},
    {'french': 'internet', 'english': 'Internet', 'turkish': 'İnternet'},
    {'french': 'web', 'english': 'web', 'turkish': 'web'},
    {'french': 'cloud', 'english': 'cloud', 'turkish': 'bulut'},
    {'french': 'cybersécurité', 'english': 'cyber security', 'turkish': 'siber güvenlik'},
    {'french': 'cryptographie', 'english': 'cryptography', 'turkish': 'kriptografi'},
    {'french': 'blockchain', 'english': 'blockchain', 'turkish': 'blok zinciri'},
    {'french': 'communication', 'english': 'communication', 'turkish': 'iletişim'},
    {'french': 'média', 'english': 'media', 'turkish': 'yarım'},
    {'french': 'presse', 'english': 'presses', 'turkish': 'presler'},
    {'french': 'radio', 'english': 'radio', 'turkish': 'radyo'},
    {'french': 'télévision', 'english': 'television', 'turkish': 'televizyon'},
    {'french': 'cinéma', 'english': 'cinema', 'turkish': 'sinema'},
    {'french': 'publicité', 'english': 'advertising', 'turkish': 'reklam'},
    {'french': 'marketing', 'english': 'marketing', 'turkish': 'pazarlama'},
    {'french': 'relations publiques', 'english': 'public relations', 'turkish': 'halkla i̇li̇şki̇ler'},
    {'french': 'propagande', 'english': 'advertising', 'turkish': 'reklam'},
    {'french': 'art', 'english': 'art', 'turkish': 'sanat'},
    {'french': 'beauté', 'english': 'beauty', 'turkish': 'güzellik'},
    {'french': 'esthétique', 'english': 'aesthetics', 'turkish': 'ESTETİK'},
    {'french': 'style', 'english': 'style', 'turkish': 'stil'},
    {'french': 'mode', 'english': 'mode', 'turkish': 'modu'},
    {'french': 'design', 'english': 'design', 'turkish': 'Tasarım'},
    {'french': 'architecture', 'english': 'architecture', 'turkish': 'mimarlık'},
    {'french': 'urbanisme', 'english': 'urbanism', 'turkish': 'şehircilik'},
    {'french': 'paysage', 'english': 'landscape', 'turkish': 'manzara'},
    {'french': 'décoration', 'english': 'decoration', 'turkish': 'dekorasyon'},
    {'french': 'philosophie', 'english': 'philosophy', 'turkish': 'felsefe'},
    {'french': 'éthique', 'english': 'ethics', 'turkish': 'ETİK'},
    {'french': 'morale', 'english': 'morale', 'turkish': 'moral'},
    {'french': 'valeur', 'english': 'value', 'turkish': 'değer'},
    {'french': 'principe', 'english': 'principle', 'turkish': 'prensip'},
    {'french': 'sagesse', 'english': 'wisdom', 'turkish': 'bilgelik'},
    {'french': 'connaissance', 'english': 'knowledge', 'turkish': 'BİLGİ'},
    {'french': 'vérité', 'english': 'truth', 'turkish': 'gerçek'},
    {'french': 'réalité', 'english': 'reality', 'turkish': 'gerçeklik'},
    {'french': 'existence', 'english': 'existence', 'turkish': 'varoluş'},
    {'french': 'bonheur', 'english': 'happiness', 'turkish': 'Mutluluk'},
    {'french': 'amour', 'english': 'amour', 'turkish': 'Aşk'},
    {'french': 'amitié', 'english': 'friendship', 'turkish': 'Arkadaşlık'},
    {'french': 'famille', 'english': 'family', 'turkish': 'AİLE'},
    {'french': 'mariage', 'english': 'mariage', 'turkish': 'mariage'},
    {'french': 'enfance', 'english': 'childhood', 'turkish': 'çocukluk'},
    {'french': 'adolescence', 'english': 'adolescence', 'turkish': 'ERGENLİK DÖNEMİ'},
    {'french': 'adulte', 'english': 'adulte', 'turkish': 'adulte'},
    {'french': 'vieillesse', 'english': 'old age', 'turkish': 'YAŞLILIK'},
    {'french': 'mort', 'english': 'death', 'turkish': 'Ölüm'},
    {'french': 'santé', 'english': 'health', 'turkish': 'sağlık'},
    {'french': 'maladie', 'english': 'disease', 'turkish': 'Hastalık'},
    {'french': 'handicap', 'english': 'handicap', 'turkish': 'handikap'},
    {'french': 'bien-être', 'english': 'well-being', 'turkish': 'iyi olma hali'},
    {'french': 'confort', 'english': 'comfort', 'turkish': 'Konfor'},
    {'french': 'repos', 'english': 'repos', 'turkish': 'repolar'},
    {'french': 'sommeil', 'english': 'sleep', 'turkish': 'uyku'},
    {'french': 'rêve', 'english': 'dream', 'turkish': 'Rüya'},
    {'french': 'cauchemar', 'english': 'cauchemar', 'turkish': 'cauchemar'},
    {'french': 'stress', 'english': 'stress', 'turkish': 'stres'},
    {'french': 'travail', 'english': 'work', 'turkish': 'iş'},
    {'french': 'carrière', 'english': 'career', 'turkish': 'kariyer'},
    {'french': 'profession', 'english': 'profession', 'turkish': 'meslek'},
    {'french': 'métier', 'english': 'business', 'turkish': 'İŞ'},
    {'french': 'emploi', 'english': 'emploi', 'turkish': 'emploi'},
    {'french': 'chômage', 'english': 'unemployment', 'turkish': 'İşsizlik'},
    {'french': 'retraite', 'english': 'retirement', 'turkish': 'emeklilik'},
    {'french': 'salaire', 'english': 'salary', 'turkish': 'maaş'},
    {'french': 'revenu', 'english': 'revenu', 'turkish': 'revenu'},
    {'french': 'richesse', 'english': 'richesse', 'turkish': 'richesse'},
    {'french': 'pauvreté', 'english': 'poverty', 'turkish': 'Yoksulluk'},
    {'french': 'égalité', 'english': 'equality', 'turkish': 'eşitlik'},
    {'french': 'inégalité', 'english': 'inequality', 'turkish': 'eşitsizlik'},
    {'french': 'discrimination', 'english': 'discrimination', 'turkish': 'ayrımcılık'},
    {'french': 'préjugé', 'english': 'prejudice', 'turkish': 'Önyargı'},
    {'french': 'stéréotype', 'english': 'stereotype', 'turkish': 'stereotip'},
    {'french': 'racisme', 'english': 'racism', 'turkish': 'IRKÇILIK'},
    {'french': 'sexisme', 'english': 'sexism', 'turkish': 'cinsiyetçilik'},
    {'french': 'homophobie', 'english': 'homophobia', 'turkish': 'homofobi'},
    {'french': 'xénophobie', 'english': 'xenophobia', 'turkish': 'yabancı düşmanlığı'},
    {'french': 'liberté', 'english': 'freedom', 'turkish': 'özgürlük'},
    {'french': 'indépendance', 'english': 'independence', 'turkish': 'BAĞIMSIZLIK'},
    {'french': 'autonomie', 'english': 'autonomies', 'turkish': 'özerklikler'},
    {'french': 'responsabilité', 'english': 'responsibility', 'turkish': 'sorumluluk'},
    {'french': 'devoir', 'english': ['homework', 'duty'], 'turkish': ['ev ödevi', 'görev']},
    {'french': 'obligation', 'english': 'obligation', 'turkish': 'Yükümlülük'},
    {'french': 'droit', 'english': 'right', 'turkish': 'doğru'},
    {'french': 'privilège', 'english': 'privilege', 'turkish': 'ayrıcalık'},
    {'french': 'honneur', 'english': 'honor', 'turkish': 'onur'},
    {'french': 'dignité', 'english': 'dignity', 'turkish': 'haysiyet'},
    {'french': 'courage', 'english': 'courage', 'turkish': 'Cesaret'},
    {'french': 'peur', 'english': 'fear', 'turkish': 'korku'},
    {'french': 'confiance', 'english': 'confiance', 'turkish': 'GÜVEN'},
    {'french': 'méfiance', 'english': 'distrust', 'turkish': 'güvensizlik'},
    {'french': 'espoir', 'english': 'hope', 'turkish': 'umut'},
    {'french': 'désespoir', 'english': 'despair', 'turkish': 'çaresizlik'},
    {'french': 'optimisme', 'english': 'optimism', 'turkish': 'iyimserlik'},
    {'french': 'pessimisme', 'english': 'pessimisms', 'turkish': 'karamsarlıklar'},
    {'french': 'joie', 'english': 'joy', 'turkish': 'NEŞE'},
    {'french': 'tristesse', 'english': 'tristesse', 'turkish': 'tristesse'},
    {'french': 'colère', 'english': 'anger', 'turkish': 'Pişmanlık'},
    {'french': 'calme', 'english': 'calm', 'turkish': 'sakin'},
    {'french': 'excitation', 'english': 'excitation', 'turkish': 'uyarma'},
    {'french': 'ennui', 'english': 'ennui', 'turkish': 'ennui'},
    {'french': 'surprise', 'english': 'surprise', 'turkish': 'Sürpriz'},
    {'french': 'déception', 'english': 'disappointment', 'turkish': 'hayal kırıklığı'},
    {'french': 'fierté', 'english': 'pride', 'turkish': 'gel'},
    {'french': 'honte', 'english': 'shame', 'turkish': 'utanç'},
    {'french': 'culpabilité', 'english': 'guilt', 'turkish': 'suçluluk duygusu'},
    {'french': 'pardon', 'english': 'pardon', 'turkish': 'Pardon'},
    {'french': 'humour', 'english': 'humour', 'turkish': 'Mizah'},
    {'french': 'rire', 'english': 'laugh', 'turkish': 'gülmek'},
    {'french': 'sourire', 'english': 'smile', 'turkish': 'gülümseme'},
    {'french': 'larme', 'english': 'larme', 'turkish': 'larme'},
    {'french': 'plaisir', 'english': 'pleasure', 'turkish': 'zevk'},
    {'french': 'douleur', 'english': 'pain', 'turkish': 'ağrı'},
    {'french': 'sensation', 'english': 'sensation', 'turkish': 'duyum'},
    {'french': 'toucher', 'english': 'touch', 'turkish': 'Dokunmak'},
    {'french': 'goût', 'english': 'taste', 'turkish': 'tat'},
    {'french': 'odorat', 'english': 'odorat', 'turkish': 'odorat'},
]

score = 0

while True:
    language = input("Choose language (english/turkish): ").strip().lower()
    if language in ["english", "turkish"]:
        break
    else:
        print("Invalid language choice. Please enter 'english' or 'turkish'.")

while True:
    try:
        if language == "english":
            num_questions = int(input(f"How many questions do you want? (1-{len(words)}): ").strip())
            if 1 <= num_questions <= len(words):
                break
            else:
                print(f"Please enter a number between 1 and {len(words)}.")
        else:
            num_questions = int(input(f"Kaç soru yapmak istersiniz? (1-{len(words)}): ").strip())
            if 1 <= num_questions <= len(words):
                break
            else:
                print(f"Lütfen 1 ile {len(words)} arasında bir sayı girin.")
    except ValueError:
        if language == "english":
            print("Invalid input. Please enter a number.")
        else:
            print("Geçersiz giriş. Lütfen bir sayı girin.")

selected_words = quiz_user(words, num_questions)
for word in selected_words:
    if language == 'english':
        print(f"Translate '{word['french']}' to {language}:")
    else: 
        print(f"'{word['french']}' kelimesini {language} diline çevirin:")
    user_answer = input().strip().lower()
    if check_answer(word, user_answer, language):
        score += 1
        if language == "english":
            print("Correct!")
            print("Score: " + str(score))
        else:
            print("Doğru!")
            print("Puanınız: " + str(score))
    else:
        score -= 1
        if language == "english":
            print(f"Wrong! The correct answer(s): {word[language]}")
            print("Score: " + str(score))
        else:
            print(f"Yanlış! Doğru cevap: {word[language]}")
        if language == "turkish":
            print("Puanınız: " + str(score))

if language == 'english':
    print(f"Your final score is: {score}/{num_questions}")
else:
    print(f"Son puanınız: {score}/{num_questions}")